### ISSUE TITLE
[Scheduler][Storageelement] Byte conversions are inconsistent and mostly wrong

### ISSUE THREAD

**Issue by HerrHorizontal** [MatterMiners/lapis.caching#10]
Size conversions of Bytes are inconsistently converted to MiB and GiB, etc.

In [`storageelement.py`](https://github.com/tfesenbecker/lapis/blob/master/lapis/storageelement.py#L101-L102) it is consistently converted with factors of `1000`.

In [`scheduler.py`]() this is sometimes converted with factors of `1000` for [`memory`](https://github.com/tfesenbecker/lapis/blob/0a79525ad0c3418893232fb084d9437b625696a5/lapis/scheduler.py#L115-L119) or `1024` for [`disk`](https://github.com/tfesenbecker/lapis/blob/0a79525ad0c3418893232fb084d9437b625696a5/lapis/scheduler.py#L120-L125).

This should be consistently changed to `1024`.

**Comment by eileen-kuehn** [comment]
@HerrHorizontal, attention here! It is not the internal usage that is inconsistent but the imported types. So it is on purpose that we sometimes use `1000` or `1024`. However, internally we should *always* deal with Bytes.

**Comment by eileen-kuehn** [comment]
Closing this, as the conversions are intentionally.
