### ISSUE TITLE
Hitrate based caching based on job-wise provision of all input files by a storage element

### ISSUE THREAD

**Issue by HerrHorizontal** [MatterMiners/lapis.caching#12]
In the current implementation either all or no input files of a job are provided by a storageelement:

https://github.com/tfesenbecker/lapis/blob/0a79525ad0c3418893232fb084d9437b625696a5/lapis/connection.py#L189

This boolean treatment introduces a strong bias, which might be negligible as long as caching and cache-eviction policies are properly configured. Therefore, the more general approach would be to sample a boolean for each requested file separately, instead of one per job.

**Comment by eileen-kuehn** [comment]
Isn't this part of the concept of the hitrate based caching scenario? I don't know exactly, but if you do, this would be a simple fix. 
Could you look up the details in the thesis of Tabea?

**Comment by HerrHorizontal** [comment]
So I checked and indeed, it seems that this is an assumption @tfesenbecker makes in her hitrate-based caching. But I think this might break as soon as one wants to study cache logics which cache blocks of files instead of the whole file.

**Comment by eileen-kuehn** [comment]
So then please open another set of tickets for requirements of block-based caching. Closing this as the current approach is valid within the given assumptions.

**Comment by HerrHorizontal** [comment]
Conceptually, this might also be a problem, when several tasks read different files to the cache. It is unclear, then, if in this case the cache still provides the full set of input files or none, when only a fraction of the required input files was loaded by previous jobs accessing the cache.

**Comment by maxfischer2781** [comment]
Sorry, I'm not following what exactly the goal is here. Yes, the current hit-rate-based-caching makes per-job decisions based on a global hit-rate. That's for Tabea's approach to model caches as black boxes, so it is per design.  
That's purposely a simplification so that one does *not* have to worry about details like cache occupancy, cache-eviction policies and such. It's decidedly not suitable for any case where such a simplification is not desirable.

Is this ticket just to document that this is the case? Is it about extending this model? Is it about adding an alternative model?

**Comment by HerrHorizontal** [comment]
> Sorry, I'm not following what exactly the goal is here. Yes, the current hit-rate-based-caching makes per-job decisions based on a global hit-rate. That's for Tabea's approach to model caches as black boxes, so it is per design.
> That's purposely a simplification so that one does _not_ have to worry about details like cache occupancy, cache-eviction policies and such. It's decidedly not suitable for any case where such a simplification is not desirable.
> 
> Is this ticket just to document that this is the case? Is it about extending this model? Is it about adding an alternative model?

Yes, it's on one hand to document this simplification, on the other hand to extend this model, since to my understanding this extension is what hit-rate-based caching should actually be like. This is also what @tfesenbecker mentions in her thesis as a simplification. She also proposes to extend this for future studies.
