### ISSUE TITLE
Code repetitions in files classes

### ISSUE THREAD

**Issue by HerrHorizontal** [MatterMiners/lapis.caching#2]
Unnecessary doublings in [/lapi/files.py](https://github.com/tfesenbecker/lapis/blob/master/lapis/files.py) present. The readability and comprehensibility could be improved by introducing a common `File` class as a parent.

**Comment by HerrHorizontal** [comment]
This will also involve issue #3.

**Comment by maxfischer2781** [comment]
I'm not seeing what a common base class would improve. The only commonality are the two fields ``"filename", "filesize"``. We would basically have to split ``RequestedFile`` into two classes, and have ``StoredFile`` delegate to ``super().__init__`` (while still taking all arguments), which seems like more complexity than listing the same fields in two locations.
