### ISSUE TITLE
Walltime of the job independent of ressource is a strong simplification

### ISSUE THREAD

**Issue by HerrHorizontal** [MatterMiners/lapis.caching#23]
@tfesenbecker quotes that the job walltime is treated as constant on all ressources. To get a realistic simulation, this is oversimplified in my opinion. Is this limitation a consequence of the design of the job ressource interplay in LAPIS or is it a configuration issue?

**Comment by HerrHorizontal** [comment]
If I understand it correctly, the caching extension only adjusted according to
```
walltime = max( calculation-time, transfer-time)
```
which still doesn't solve the underlying simplification of the calculation-time beeing independent of the ressource.

**Comment by eileen-kuehn** [comment]
Yes, currently resources are not distinguished with respect to any computational properties. One of the reasons for this is that we don't have any data or models for the wall time of jobs how they would run on different resources. Therefore, wall time is treated equally. If you like you could define the wall times of your jobs with respect to varying resources. So a job does not have a single wall time, but a dictionary of several.

**Comment by maxfischer2781** [comment]
Do you have a specific model for runtime in mind? A simple model would be to assign each Worker a scaling factor for the calculation time. If we wanted to go a bit further, one could simulate congestion of the worker's resources – not sure how to model that though.

--------

For the simple case, the job could apply the factor inside ``_calculate`` if we pass along the drone.

https://github.com/MatterMiners/lapis.caching/blob/41409832dfa9e026994f605dea347aac7d80cc10/lapis/cachingjob.py#L230-L257

Or of course one could flatten the entire ``run`` method a bit to do roughly this:

```python3
    async def run(self, drone: "Drone"):
            ...
            async with Scope() as scope:
                await instant
                scope.do(
                    self.drone.connection.transfer_files(
                        drone=drone, requested_files=self.used_inputfiles, job_repr=self
                ))
                calculation_duration = drone.calculation_factor * self.walltime / self.calculation_efficiency
                scope.do(time + calculation_duration)
```

**Comment by HerrHorizontal** [comment]
seems to me the underlying problem is that walltime isn't really a good metric for the processed information content of a job. If we could find an invariant quantity defining the amount of information which "flows" through each resource, we wouldn't need to define a dict of walltimes.

Generally I think it might be beneficial to identify such invariant quantities representing all the defining properties of the jobs, resources, pipes, etc. I kinda have a type of "information flux model" in mind.

**Comment by HerrHorizontal** [comment]
> Yes, currently resources are not distinguished with respect to any computational properties. One of the reasons for this is that we don't have any data or models for the wall time of jobs how they would run on different resources. Therefore, wall time is treated equally. If you like you could define the wall times of your jobs with respect to varying resources. So a job does not have a single wall time, but a dictionary of several.

Seems to me the underlying problem is that walltime isn't really a good metric for the processed information content of a job. If we could find an invariant quantity defining the amount of information which "flows" through each resource, we wouldn't need to define a dict of walltimes.

Generally I think it might be beneficial to identify such invariant quantities representing all the defining properties of the jobs, resources, pipes, etc. I kinda have a type of "information flux model" in mind.
