### ISSUE TITLE
Enable multiple sites with different schedulers for simulator

### ISSUE THREAD

**Issue by HerrHorizontal** [MatterMiners/lapis.caching#26]
Currently, it is not possible to generate multiple schedulers per simulator object. This feature might be required, when simulating multiple sites with different negotiation services.

**Comment by eileen-kuehn** [comment]
This is already possible given the current implementation and is part of the concept of lapis but does not work out of the box with the standard provided simulator. Just go ahead and perform the adaptations that you need :)
