### ISSUE TITLE
[Job] restructure single job class to dedicated ones

### ISSUE THREAD

**Issue by HerrHorizontal** [MatterMiners/lapis.caching#5]
Currently there is only one [job class](https://github.com/tfesenbecker/lapis/blob/0a79525ad0c3418893232fb084d9437b625696a5/lapis/job.py#L12) defined. It might be nice for future extensions, to define a base job class with basic functionality and split the input file and caching functionalities into a dedicated job class which inherits its base functionalities from the base class.

**Comment by eileen-kuehn** [comment]
The [`job` as defined by LAPIS](https://github.com/MatterMiners/lapis/blob/dccf8cfed602cc54962092a1c831458c418ec920/lapis/job.py#L13-L115) is the base job definition that can further be extended. This is what @tfesenbecker did with her caching extension.

**Comment by HerrHorizontal** [comment]
> The [`job` as defined by LAPIS](https://github.com/MatterMiners/lapis/blob/dccf8cfed602cc54962092a1c831458c418ec920/lapis/job.py#L13-L115) is the base job definition that can further be extended. This is what @tfesenbecker did with her caching extension.

In this case, this issue is solved and can be closed.
