### ISSUE TITLE
Naming and usage of RemoteStorage misleading

### ISSUE THREAD

**Issue by HerrHorizontal** [MatterMiners/lapis.caching#7]
The current implementation of a [`RemoteStorage`](https://github.com/tfesenbecker/lapis/blob/0a79525ad0c3418893232fb084d9437b625696a5/lapis/storageelement.py#L13) as a global storage which contains all files globally available with one infinite bandwidth is doubtful. There is no such storage element in a real setup, but rather several remote storages with different connections and final bandwidths. These are to my understanding configurable as single storage elements of type [`StorageElement`](https://github.com/tfesenbecker/lapis/blob/0a79525ad0c3418893232fb084d9437b625696a5/lapis/storageelement.py#L77).

I suggest to keep the global storage as a fall-back, but rename it to avoid confusion. On the long run this type of storage should not be necessary anyway in the simulation.

**Comment by eileen-kuehn** [comment]
Could you provide a reference to the code where an instance of `RemoteStorage` is actually instantiated with infinite `throughput` (intentionally and not in terms as a fallback)? As much as I can see the storage is expected to model a WLCG storage. Therefore, it does provide infinite storage to properly provide all files but gets instantiated with a predefined `throughput`. Please note, that the `throughput` also doesn't have a default value that might unintentionally lead to an infinite `throughput`.
So as long as the person setting up the simulation properly takes care to select reasonable values for the `throughput`, I don't see any issues here. Also the naming is fine from my point of view. But if you can imagine something better, please let us know or submit a PR.

**Comment by HerrHorizontal** [comment]
Okay, so this type of storage is intended as a fallback or a dummy? In this case, this issue can be closed. Maybe, it would be good then, to make clear, that this is not intended to be used for a simulation which tries to reproduce the behavior of a setup with more than one WLCG storage, which share files. 

Although, this case could then also be caught by introducing more than one connection to the storage. But according to my knowledge this is currently not supported, isn't it?

**Comment by eileen-kuehn** [comment]
> this case could then also be caught by introducing more than one connection to the storage. But according to my knowledge this is currently not supported, isn't it?

With the current state of the code, this is not supported, correctly. But I already have a draft for completely replacing the concept of current `Connection` classes with something comparable to namespaces mimicking the behaviour of xrootd. This will indeed enable the setup you are intending  (at least I hope so) allowing several `StorageElement`s at different levels of the hierarchy independent of its type.

I would propose leaving this as is and enjoying future extensions instead :)
