### ISSUE TITLE
Chosing the caching scenario via CLI

### ISSUE THREAD

**Issue by HerrHorizontal** [MatterMiners/lapis.caching#8]
Basic functionality for file-based and hitrate-based caching are rudimentary already implemented in the [`connection`](https://github.com/tfesenbecker/lapis/blob/master/lapis/connection.py) module (see issue #6 for further improvements and restructuring). The option of choosing one of these scenarios should be configurable.

**Comment by HerrHorizontal** [comment]
This also involves issue #9.

**Comment by HerrHorizontal** [comment]
This has been fixed by #24.

**Comment by eileen-kuehn** [comment]
The appropriate PR #17 is not merged yet, so this shouldn't be closed yet.

**Comment by HerrHorizontal** [comment]
> The appropriate PR #17 is not merged yet, so this shouldn't be closed yet.

Okay, however the necessary changes have been finalized in #24.
