### ISSUE TITLE
Enable configuration of storage types via CLI

### ISSUE THREAD

**Issue by HerrHorizontal** [MatterMiners/lapis.caching#9]
At the current state, the cli [`simulate.py`](https://github.com/tfesenbecker/lapis/blob/master/lapis/cli/simulate.py) allows only one `storage_type` to be chosen. Also it isn't possible to define more than one storage element.

**Comment by HerrHorizontal** [comment]
This was attempted by #24, but not fully pulled off. While making multiple storage elements configurable via CLI, the type is still hard-coded. I suggest adding a tuple-parameter to `storage_files` in https://github.com/MatterMiners/lapis.caching/blob/add/initial-code/lapis/cli/simulate.py#L80-L91, which also includes the `storage_type`.

**Comment by eileen-kuehn** [comment]
Could you please clarify the description of this issue? What do you mean with choosing of one storage element? What are the relevant points of issues #6 and #8?
And to which choice are you referring to in the last sentence?

**Comment by HerrHorizontal** [comment]
> Could you please clarify the description of this issue? What do you mean with choosing of one storage element? What are the relevant points of issues #6 and #8?
> And to which choice are you referring to in the last sentence?

see above
